esphome:
  name: pipower-pro
  friendly_name: PiPower-Pro

esp32:
  board: esp32-s2-saola-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "wuJrEm4L6udD3LDWObzzhUzJMRAQH8GBZQljsX5AQi4="

ota:
  password: "a2f47d3677ff92ba9ef2a2ba274e68c3"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pipower-Pro Fallback Hotspot"
    password: "IRRW7cbQo71j"

captive_portal:

packages:
  # sunfounder.pipower-pro: github://sunfounder/pipower-pro/pipower-pro-template.yaml@main
  pipower-pro: !include pipower-pro-template.yaml
