substitutions:
  name: pipower-pro
  friendly_name: PiPower Pro

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  comment: Smart UPS module
  # name_add_mac_suffix: true
  project:
    name: "sunfounder.pipower-pro"
    version: "v1.0.0"
  includes:
    - current_control.h

esp32:
  board: esp32-s2-saola-1
  framework:
    type: arduino

logger:
  level: WARN

api:

ota:

dashboard_import:
  package_import_url: github://sunfounder/pipower-pro/test-template.yaml@main
  import_full_config: false # or true

wifi:
  ap:
    password: "12345678"

captive_portal:

improv_serial:

text_sensor:
  # Version
  - platform: template
    name: "Version"
    id: pipower_pro_version
    lambda: |-
      return {"Hello World"};
